### ISSUE TITLE
Картинка 3-й лабы не работает с PyGame 1.9

### ISSUE THREAD

**Issue by tkhirianov** [NailKhas/Infa_Nail#2]
Не запускается картинка, не могу посмотреть и проверить. (И поставить оценку)
Полагаю, что это связано с версией библиотеки.
Явно проблема с округлением (его отсутствием).

Вот ошибка:

```
(base) tkhirianov@tknote:~/work/students/NailKhas/Infa_Nail$ python lab3_3.py 
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "lab3_3.py", line 37, in <module>
    hedge(170, 520, 0.5)
  File "lab3_3.py", line 30, in hedge
    circle(screen, (0, 0, 0), (x + 262 * size, y + 55 * size), 5 * size)
TypeError: integer argument expected, got float
```

**Comment by tkhirianov** [comment]
Почему так долго нет реакции?...

**Comment by tkhirianov** [comment]
я вижу, что ты залил сюда картинку одним коммитом 01412b2d3
ЗНачит так и бага.

**Comment by tkhirianov** [comment]
Забей! С библиотекой PyGame 2.0.1 всё заработало.
